pythonqa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

import debug_toolbar

from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

import os
from .settings import BASE_DIR
from django.conf.urls.static import static


admin.sites.AdminSite.site_header = '后台管理系统'
admin.sites.AdminSite.site_title = '标题党'
admin.sites.AdminSite.index_title = '你想干嘛就干嘛'

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    url(r'^', include('qa.urls')),
    url(r'^', include('core.urls')),
    url('avatar/', include('avatar.urls')),
] + static('avatars/', 
    document_root=os.path.join(BASE_DIR, 'avatars')
) + static('avatar/change/avatars/',
    document_root=os.path.join(BASE_DIR, 'avatars')
)

qa/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.QuestionIndexView.as_view(), name='qa_index'),

    url(r'^question/(?P<pk>\d+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/answer/(?P<answer_id>\d+)/$',
        views.AnswerQuestionView.as_view(), name='qa_answer_question'),

    url(r'^question/close/(?P<question_id>\d+)/$',
        views.CloseQuestionView.as_view(), name='qa_close_question'),

    url(r'^new-question/$', views.CreateQuestionView.as_view(),
        name='qa_create_question'),

    url(r'^edit-question/(?P<question_id>\d+)/$',
        views.UpdateQuestionView.as_view(),
        name='qa_update_question'),

    url(r'^answer/(?P<question_id>\d+)/$',
        views.CreateAnswerView.as_view(), name='qa_create_answer'),

    url(r'^answer/edit/(?P<answer_id>\d+)/$',
        views.UpdateAnswerView.as_view(), name='qa_update_answer'),

    url(r'^vote/question/(?P<object_id>\d+)/$',
        views.QuestionVoteView.as_view(), name='qa_question_vote'),

    url(r'^vote/answer/(?P<object_id>\d+)/$',
        views.AnswerVoteView.as_view(), name='qa_answer_vote'),

    url(r'^comment-answer/(?P<answer_id>\d+)/$',
        views.CreateAnswerCommentView.as_view(),
        name='qa_create_answer_comment'),

    url(r'^comment-question/(?P<question_id>\d+)/$',
        views.CreateQuestionCommentView.as_view(),
        name='qa_create_question_comment'),

    url(r'^comment-question/edit/(?P<comment_id>\d+)/$',
        views.UpdateQuestionCommentView.as_view(),
        name='qa_update_question_comment'),

    url(r'^comment-answer/edit/(?P<comment_id>\d+)/$',
        views.UpdateAnswerCommentView.as_view(),
        name='qa_update_answer_comment'),

    url(r'^search/$', views.QuestionsSearchView.as_view(), name='qa_search'),

    url(r'^tag/(?P<tag>[-\w]+)/$',
        views.QuestionsByTagView.as_view(), name='qa_tag'),

    url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='qa_profile'),

    url('^markdown/', include('django_markdown.urls')),

    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]

qa/models.py
from annoying.fields import AutoOneToOneField
from django.conf import settings
from django.db import models
from django.db.models import F
# from django.utils.text import slugify
from uuslug import slugify
from django_markdown.models import MarkdownField
from hitcount.models import HitCountMixin
from taggit.managers import TaggableManager


class UserQAProfile(models.Model):
    """Model class to define a User profile for the app, directly linked
    to the core Django user model."""
    user = AutoOneToOneField(settings.AUTH_USER_MODEL, primary_key=True,
                             on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)

    def modify_reputation(self, added_points):
        """Core function to modify the reputation of the user profile."""
        self.points = F('points') + added_points
        self.save()

    def __str__(self):  # pragma: no cover
        return self.user.username


class Question(models.Model, HitCountMixin):
    """Model class to contain every question in the forum"""
    slug = models.SlugField(max_length=200)
    title = models.CharField(max_length=200, blank=False, verbose_name='标题')
    description = MarkdownField(verbose_name='描述')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    tags = TaggableManager(verbose_name='标签', help_text='逗号分隔(",").')
    reward = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    closed = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)

    class Meta:
        ordering = ['-pub_date']

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
            try:
                points = settings.QA_SETTINGS['reputation']['CREATE_QUESTION']

            except KeyError:
                points = 0

            self.user.userqaprofile.modify_reputation(points)

        self.total_points = self.positive_votes - self.negative_votes
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Answer(models.Model):
    """Model class to contain every answer in the forum and to link it
    to the proper question."""
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = MarkdownField(verbose_name='您的回答')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    updated = models.DateTimeField('date updated', auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    answer = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_ANSWER']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        self.total_points = self.positive_votes - self.negative_votes
        super(Answer, self).save(*args, **kwargs)

    def __str__(self):  # pragma: no cover
        return self.answer_text

    class Meta:
        ordering = ['-answer', '-pub_date']


class VoteParent(models.Model):
    """Abstract model to define the basic elements to every single vote."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    value = models.BooleanField(default=True)

    class Meta:
        abstract = True


class AnswerVote(VoteParent):
    """Model class to contain the votes for the answers."""
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('user', 'answer'),)


class QuestionVote(VoteParent):
    """Model class to contain the votes for the questions."""
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('user', 'question'),)


class BaseComment(models.Model):
    """Abstract model to define the basic elements to every single comment."""
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def __str__(self):  # pragma: no cover
        return self.comment_text


class AnswerComment(BaseComment):
    """Model class to contain the comments for the answers."""
    comment_text = MarkdownField()
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_ANSWER_COMMENT']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        super(AnswerComment, self).save(*args, **kwargs)


class QuestionComment(BaseComment):
    """Model class to contain the comments for the questions."""
    comment_text = models.CharField(max_length=250, verbose_name='您的评论')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_QUESTION_COMMENT']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        super(QuestionComment, self).save(*args, **kwargs)

qa/forms.py
from django import forms
from django.conf import settings
from qa.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'description', 'tags']
        labels = {
            'title': '标题',
            'description': '描述',
            'tags': '标签',
        }

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)

        try:
            settings.QA_SETTINGS['qa_description_optional']
            self.fields['description'].required = not settings.QA_SETTINGS[
                'qa_description_optional']

        except KeyError:
            pass

qa/templates/qa/base.html
{% load staticfiles %}
{% load bootstrap3 %}
{% load avatar_tags %}
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>尘归尘{% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/png" href="{% static 'qa/icon.ico' %}">
    <script src="https://cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>

    <!-- <link href='//fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'> -->
    <!-- <link href='//fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'> -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="{% static 'css/qa.css' %}" rel="stylesheet"/>
  </head>
  <body>
    <div class="topbar">
      <a class="btn btn-lg" href="#search">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> 查&nbsp;&nbsp;询 </a>
      <a class="btn btn-lg" href="{% url 'qa_create_question' %}">
         <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 发现问题 </a>
      <div id="user_avatar">
        {% if user.is_authenticated %}
          {% avatar user 35 class="img-circle img-responsive head-ding" %}
        {% else %}
          <h3><a class="head-ding" href="{% url 'login' %}">登 录</a></h3>
        {% endif %}
    <!--       {% if user.is_authenticated %}
            {{ user.username }}
        {% endif %} -->
        <div class="info" id="disinfo">
          <ul class="ul-user">
          {% if user.is_authenticated %}
              <li>昵称：<strong>{{ user.username }}</strong></li>
              {% if user.is_superuser %}
                  <li><a href="{% url 'admin:index' %}">管理面板</a></li>
              {% endif %}
              <li><a href="#">更改密码</a></li>
              <li><a href="{% url 'logout' %}">注 销</a></li>
          {% endif %}
          </ul>
          <div class="navl navl-background"></div>
        </div>
      </div>
    </div>
    <div class="container">
      
      <h1>
        <a href="{% url 'qa_index' %}">
        <img width="50px" src="{% static 'qa/wenhao.png' %}" />
        等你来提问</a>
        <small>无所不知</small>
      </h1>
      </div>
    </div>

    <div class="container">
      {% if messages %}
      {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
      {% endfor %}
      {% endif %}
      {% block content %}

      {% endblock content %}
      <div id="search">
        <button type="button" class="close">×</button>
        <form method="GET" action="{% url 'qa_search' %}">
          <input type="search" value="" name="word" placeholder="你想找什么呢？" />
          <input class="btn btn-lg btn-warning" type="submit" value="查找" />
        </form>
  
      </div>
    </div>
    <hr>
    <center>
      <a href="http://www.djangoproject.com/"><img src="https://www.djangoproject.com/m/img/badges/djangoproject120x25.gif" border="0" alt="A Django project." title="A Django project." /></a> ·
      <a href="https://gitee.com/yx_520/tiaopi">Github</a> ·
      <a data-toggle="modal" data-target="#apiModal">API</a> ·
      <small><a href="/admin">管理面板</a></small>
    </center>
      <br/><br/>


    <!-- Modal -->
    <div class="modal fade" id="apiModal" tabindex="-1" role="dialog" aria-labelledby="APIModal" aria-hidden="true">
      <div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span> API Access</h4>
    </div>
    <div class="modal-body">
            <ul>
              <li>
   <b>问题清单</b>
   <br/>重新排列问题清单.
   <br/>json URL : <code class="custom-code">http://djangoqa.azurewebsites.net/api/questions/?format=json</code>
              </li>
              <br/>
              <li>
   <b>用户列表</b>
   <br/>检索用户列表.
   <br/>json URL : <code class="custom-code">http://djangoqa.azurewebsites.net/api/users/?format=json</code>
              </li>
            </ul>
    </div>
    <div class="modal-footer">
            <button type="button" class="btn btn-info" data-dismiss="modal">关闭</button>
    </div>
  </div>
      </div>
    </div>

    {% block js %}
    <script>
      $(function () {
        $('a[href="#search"]').on('click', function(event) {
          event.preventDefault();
          $('#search').addClass('open');
          $('#search > form > input[type="search"]').focus();
          });

          $('#search, #search button.close').on('click keyup', function(event) {
            if (event.target == this || event.target.className == 'close' || event.keyCode == 27) {
            $(this).removeClass('open');
          }
        });
          $('#user_avatar').hover(function(){
            var de = $('#user_avatar > h3 > a').text();
            if(de == '登 录')
              $('#disinfo').hide();
            else
              $('#disinfo').show();
          },function(){
            $('#disinfo').hide();
          });
      });
    </script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% endblock js %}
    {%block extra_js %}{% endblock extra_js %}

  </body>
</html>

qa/templates/qa/create_answer.html
{% extends 'qa/base.html' %}
{% load django_markdown %}

{% block content %}

  {% if message %}
  <strong>输入有效的问题!</strong>
  {% endif %}

  <form method="post" action="{% block action_url %}{% url 'qa_create_answer' view.kwargs.question_id %}{% endblock action_url %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn pull-right btn-success" type="submit" value="提交 回答" />
  </form>

</div>

{% endblock content %}

{% block extra_js %}
  {% markdown_editor "#id_answer_text" %}
  {% markdown_media %}
{% endblock %}

qa/templates/qa/create_comment.html
{% extends 'qa/base.html' %}
{% load django_markdown %}

{% block content %}

  {% if message %}
    <strong>输入有效的问题!</strong>
  {% endif %}

  <form method="post" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn pull-right btn-success" type="submit" value="提交 评论" />
  </form>

</div>

{% markdown_editor "#ans" %}
{% markdown_media %}
{% endblock content %}

qa/templates/qa/create_question.html
{% extends 'qa/base.html' %}
{% load django_markdown %}

{% block content %}

  {% if message %}
  <strong>输入有效的问题!</strong>
  {% endif %}

  <form method="post" action="{% block action_url %}{% url 'qa_create_question' %}{% endblock action_url %}">
    {{ form.as_p }}
    {% csrf_token %}
    <input class="btn pull-right btn-success" type="submit" value="提交问题" />
  </form>

</div>

{% endblock content %}

{% block extra_js %}
  {% markdown_editor "#id_description" %}
  {% markdown_media %}
{% endblock extra_js %}

qa/templates/qa/detail_question.html
{% extends 'qa/base.html' %}
{% load django_markdown %}
{% load staticfiles %}

{% block content %}

{% if question.closed %}
  <div class="closed"></div>
{% else %}
    {% if question.reward %}
    <div class="rewarding"></div>
    {% else %}
    <div class="open"></div>
    {% endif %}
{% endif %}


{% if message %}
    <div class="alert alert-danger" role="alert">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endif %}
{% comment %}

{% if question.reward %}
    <div class="alert alert-info" role="alert">这个问题问的好 <b>{{ question.reward }}<b> 点赞!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endif %}
{% endcomment %}

<div class="jumbotron">
  <div class="row">
    {% if user.is_authenticated and question.user != user %}
      <div class ="col-sm-1">
        <big class="pull-left custom-big"><b>{{ question.total_points }}</b></big>
      </div>
      <div class ="col-sm-1">
        <form action="{% url 'qa_question_vote' question.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <input type="hidden" name="upvote" value="on">
          <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Vote Up this answer"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
        </form>
          <form action="{% url 'qa_question_vote' question.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Vote Down this answer"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></button>
        </form>
      </div>
    {% endif %}
    <div class="col-sm-10">
      <small class="pull-right">发表人 {{ question.user.username }}, {{ question.pub_date }}</small>
      {% if user.is_authenticated and question.user == user %}<a href="{% url 'qa_update_question' question.id %}"><small class="pull-right">退出 &nbsp;</small></a>{% endif %}
      <h3><cool>Q: </cool>{{ question.title }}</h3>
      <h4>{{ question.description|markdown }}</h4>
      <p>
      {% if question.closed %}
          <p class="pull-right">这个问题已经关闭了.</p>
      {% else %}
          <a class="btn btn-primary btn-sm pull-right" href="{% url 'qa_create_answer' question.id %}" role="button"> 回 答 ! </a>
          <a class="btn btn-primary btn-sm pull-right" href="{% url 'qa_create_question_comment' question.id %}" role="button"> 评 论 ! </a>
          <form action="{% url 'qa_close_question' question.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}"/>
            <button type="submit" class="btn btn-warning btn-sm pull-right" data-toggle="tooltip" data-placement="bottom"> 关 闭 </button>
          </form>
      {% endif %}
      </p>
    </div>
  </div>
</div>
{% if last_comments %}
  <h4>comments</h4>
  {% for comment in last_comments %}
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
    <p><b>{{ comment.comment_text|markdown }}</b><small>, <a href="{% url 'qa_profile' comment.user.id %}">{{ comment.user.username }}</a> <div class="pull-right">{{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa_update_question_comment' comment.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
    </div>
  </div>
  {% endfor %}
{% endif %}
{% if answers %}
  <h3>Answers</h3>
  <hr/>

    {% for answer in answers %}
    <div class="row">
      {% if user.is_authenticated and answer.user != user %}
      <div class ="col-md-1">
        <div class="row">
          <div class ="col-sm-1"><big class="pull-left custom-big"><b>{{ answer.total_points }}</b></big></div>
          <div class ="col-sm-1">
          <form action="{% url 'qa_answer_vote' answer.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <input type="hidden" name="upvote" value="on">
              <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Vote Up this answer"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
          </form>
          <form action="{% url 'qa_answer_vote' answer.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Vote Down this answer"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></button></div>
          </form>
        </div>
      </div>
      {% endif %}
      <div class ="col-md-9">
        <a href="{% url 'qa_create_answer_comment' answer.id %}" class="pull-right"><small><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comment &nbsp;</small></a>
        {% if answer.user == user %}<a href="{% url 'qa_update_answer' answer.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
            <div id="ans" class="alert alert-primary" role="alert">{{ answer.answer_text|markdown }}</div>
        {% if answer.answercomment_set %}
          {% for comment in answer.answercomment_set.all %}
            <p><b>{{ comment.comment_text|markdown }}</b><small>, <a href="{% url 'qa_profile' comment.user.id %}">{{ comment.user.username }}</a> <div class="pull-right">{{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa_update_answer_comment' comment.id %}" class="pull-right"><small>退出 &nbsp;</small></a>{% endif %}
          <hr>
          {% endfor %}
        {% endif %}
      </div>
          <div class ="col-md-2">
            {% if answer.user.userqaprofile.picture %}
                <img class="pull-right" src="{{ answer.user.userqaprofile.picture }}">
            {% else %}
                <img class="pull-right" width="50px" height="50px" src="{% static "qa/user.png" %}">
            {% endif %}
            <p class="pull-right">- <b><a href="{% url 'qa_profile' answer.user.id %}">{{ answer.user.username }}</a> ({{ answer.user.userqaprofile.points }})</b></p>
                {% if user.is_authenticated and answer.question.user == user and answer.question.closed == False %}
                    <form action="{% url 'qa_answer_question' answer.id %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}"/>
                        <button type="submit" class="btn btn-success btn-sm pull-right" data-toggle="tooltip" data-placement="bottom" title="Mark as answer"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button></div>
                    </form>
                {% else %}
                    {% if  answer.answer == True %}
                        <button class="btn btn-success btn-sm pull-right" title="Picked Answer"><span class="glyphicon glyphicon-star" aria-hidden="true"></span></button></div>
                    {% endif %}
                {% endif %}
          </div>
    </div>
  <hr>
    {% endfor %}

{% else %}
<img class="pull-right" src="{% static "qa/question.jpg" %}" alt="question"/>
<center><h2>这个问题仍然是开放的, <a href="{% url 'qa_create_answer' question.id %}" role="button">神回复!</a></h2></center>
{% endif %}


{% endblock content %}
{% block extra_js %}
<script src="https://cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>
<script>
  $(function () {
    // $('[data-toggle="tooltip"]').tooltip()
  });
</script>
{% endblock extra_js %}

qa/templates/qa/profile.html
{% extends 'qa/base.html' %}
{% load django_markdown %}

{% block content %}
<h2 class="pull-right">点赞 : {{ user.points }}</h1>
<ul>
  <li><b>网站 :</b> {{ user.website }} </li>
   <li><b>邮箱 :</b> {{ user.user.email }} </li>
   <li><b>加入日期 :</b> {{ user.user.date_joined }} </li>
   <li><b>最后登录日期 :</b> {{ user.user.last_login }} </li>
   <li><b>活动 :</b> {{ user.user.is_active }} </li>
<ul>

</div>
{% endblock content %}

qa/templates/qa/update_answer.html
{% extends 'qa/create_answer.html' %}

{% block action_url %}
{% url 'qa_update_answer' view.kwargs.answer_id %}
{% endblock action_url %}

qa/templates/qa/update_question.html
{% extends 'qa/create_question.html' %}

{% block action_url %}
{% url 'qa_update_question' view.kwargs.question_id %}
{% endblock action_url %}